"""Smooth anti-aliased bitmap font data for PicoWeather.

Generated by tools/generate_font.py from Arial Bold.
2-bit depth (4 alpha levels) for anti-aliased rendering.
Digits 0-9 and minus sign only.

Glyph data loaded from binary files in fonts/ directory to avoid
base64 decode memory overhead on MicroPython.
"""

LARGE_WIDTH = 65
LARGE_HEIGHT = 84
SMALL_WIDTH = 22
SMALL_HEIGHT = 28

_cache = {}

# Resolve fonts directory relative to this module's location.
# On Pico, __file__ may not exist; fonts/ is in the root CWD.
try:
    import os.path as _osp
    _dir = _osp.join(_osp.dirname(__file__), "font_data") + _osp.sep
except Exception:
    _dir = "font_data/"


def _load(size, ch):
    key = (size, ch)
    data = _cache.get(key)
    if data is not None:
        return data
    name = "minus" if ch == "-" else ch
    try:
        with open(_dir + size + "_" + name + ".bin", "rb") as f:
            data = f.read()
        _cache[key] = data
        return data
    except OSError:
        return None


def draw_char(display, ch, x, y, r, g, b, size="large"):
    """Draw anti-aliased character with additive blending."""
    if size == "large":
        w, h = LARGE_WIDTH, LARGE_HEIGHT
    else:
        w, h = SMALL_WIDTH, SMALL_HEIGHT
    data = _load(size, ch)
    if data is None:
        return
    for row in range(h):
        row_off = row * w
        for col in range(w):
            idx = row_off + col
            level = (data[idx >> 2] >> ((3 - (idx & 3)) << 1)) & 3
            if level:
                display.add_pixel(x + col, y + row,
                                  r * level // 3, g * level // 3,
                                  b * level // 3)


def measure_string(text, size="large", spacing=2):
    """Return pixel width of a string."""
    if size == "large":
        w = LARGE_WIDTH
    else:
        w = SMALL_WIDTH
    n = len(text)
    if n == 0:
        return 0
    return n * w + (n - 1) * spacing


def draw_string(display, text, x, y, r, g, b, size="large", spacing=2):
    """Draw a string of characters with additive blending."""
    if size == "large":
        w = LARGE_WIDTH
    else:
        w = SMALL_WIDTH
    for ch in text:
        draw_char(display, ch, x, y, r, g, b, size)
        x += w + spacing
